#!/usr/bin/env bash

HOOK_PATH=".git/hooks/commit-msg"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
UUID=$(uuidgen)

cat >"$HOOK_PATH" <<EOF
#!/usr/bin/env bash
# File generated by geosystems ©
# Generation timestamp: $TIMESTAMP
# Commit Hook ID (UUID): $UUID

ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=commit-msg)

HERE="\$(cd "\$(dirname "\$0")" && pwd)"
REPO_ROOT="\$(dirname "\$(dirname "\$HERE")")"
ARGS+=(--hook-dir "\$HERE" -- "\$@")

VENV_DIR="\$REPO_ROOT/.venv"
PYTHON="\$VENV_DIR/bin/python"

if [ ! -x "\$PYTHON" ]; then
    echo "Creating virtual environment in \$VENV_DIR..."
    python3 -m venv "\$VENV_DIR" || {
        echo "Failed to create virtual environment." >&2
        exit 1
    }
fi

"\$PYTHON" -m pip install --upgrade pip >/dev/null 2>&1

"\$PYTHON" -c "import pre_commit" 2>/dev/null
if [ \$? -ne 0 ]; then
    echo "Installing pre-commit inside virtual environment..."
    "\$PYTHON" -m pip install pre-commit || {
        echo "Failed to install pre-commit in virtual environment." >&2
        exit 1
    }
fi

exec "\$PYTHON" -mpre_commit "\${ARGS[@]}"
EOF

chmod +x "$HOOK_PATH"
echo "Installed commit-msg hook at $HOOK_PATH"
